version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5020:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3010:5000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
